### PR TITLE
Add minimal travis config file

### PR DESCRIPTION
**Pull request by malaterre**

### CODE REVIEW

**Comment by malaterre** [comment]
`test `rule will fails with:

```
  Error Message:
   System.IO.FileNotFoundException : Could not find file '/home/travis/build/malaterre/charls-native-dotnet/bin/Debug\DataFiles\t8c0e0.jls'.
  Stack Trace:
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
```

**Comment by malaterre** [comment]
`dotnet test` is currently failing on `focal` since libcharls2 was providing `/usr/lib/x86_64-linux-gnu/libCharLS.so.2.0` (case sensitive issue).

**Comment by vbaderks** [comment]
Hi Mathieu,

Some feedback:
- There is already an existing Azure CI pipeline configured. This CI pipeline can also build Linux targets. I think it is easier to only maintain 1 single CI pipeline.
- The proposal install the latest packed CharLS version (libcharls2). During development it is however needed to use the latest version of the CharLS version from the sub-module. Otherwise it becomes impossible to add a new C API and a C# function that uses that new function. End-users should probably use indeed apt-get install libcharls2 in most cases.

**Comment by malaterre** [comment]
I see it now at 819fa8b0cc71b93e37b86ed487593cb92e1fa8b5. Feel free to close then.

**Pull request closed without merging**
